const PharmaciesPath = 'Pharmacies/';
const PatientsPath = 'Patients/';
const MedicationsPath = 'Medications/';
const AuthPath = 'Auth/';
const PagePath = 'Page/';

export const getters = {
    //PATIENTS
    FILTERED_PATIENTS: 'FILTERED_PATIENTS',
    PATIENTS_COUNT: 'PATIENTS_COUNT',
    PATIENTS_AT_CURRENT_PAGE: 'PATIENTS_AT_CURRENT_PAGE',
    IS_PATIENT_ASSIGNED_TO_PHARMACY: 'IS_PATIENT_ASSIGNED_TO_PHARMACY',
    PATIENTS_PAGE_COUNT: 'PATIENTS_PAGE_COUNT',
    PATIENT_INDEX: 'PATIENT_INDEX',
    PATIENT_RELATED_PHARMACY_INDEX: 'PATIENT_RELATED_PHARMACY_INDEX',
    GET_PATIENT_BY_ID: 'GET_PATIENT_BY_ID',

    //PHARMACIES
    PHARMACIES: 'PHARMACIES',
    PHARMACIES_COUNT: 'PHARMACIES_COUNT',
    PHARMACIES_AT_CURRENT_PAGE: 'PHARMACIES_AT_CURRENT_PAGE',
    PHARMACIES_PAGE_COUNT: 'PHARMACIES_PAGE_COUNT',
    PHARMACY_INDEX: 'PHARMACY_INDEX',
    PHARMACY_RELATED_PATIENT_INDEX: 'PHARMACY_RELATED_PATIENT_INDEX',
    GET_PHARMACY_BY_ID: 'GET_PHARMACY_BY_ID',

    //MEDICATIONS
    MEDICATIONS: 'MEDICATIONS',

    //AUTH
    AUTH_ROLE: 'AUTH_ROLE',
    AUTH_ID: 'AUTH_ID',

    //PAGE
    ITEMS_FROM: 'ITEMS_FROM',
    ITEMS_TO: 'ITEMS_TO',
    PAGE_SIZE: 'PAGE_SIZE',
}

export const mutations = {
    //PATIENTS
    PATIENT_ADD_PHARMACY: 'PATIENT_ADD_PHARMACY',
    PATIENT_REMOVE_PHARMACY: 'PATIENT_REMOVE_PHARMACY',
    LOAD_PATIENTS_TO_STORE: 'LOAD_PATIENTS_TO_STORE',
    SET_NUMBER_OF_MONTH_TO_FILTER: 'SET_NUMBER_OF_MONTH_TO_FILTER',
    IS_PATIENT_ASSIGNED_TO_PHARMACY: 'IS_PATIENT_ASSIGNED_TO_PHARMACY',

    //PHARMACIES
    LOAD_PHARMACIES_TO_STORE: 'LOAD_PHARMACIES_TO_STORE',
    PHARMACY_ADD_PATIENT: 'PHARMACY_ADD_PATIENT',
    PHARMACY_REMOVE_PATIENT: 'PHARMACY_REMOVE_PATIENT',

    //MEDICATIONS
    LOAD_MEDICATIONS_TO_STORE: 'LOAD_MEDICATIONS_TO_STORE',

    //AUTH
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT:'AUTH_LOGOUT',

    //PAGE
    NEXT_PAGE: 'NEXT_PAGE',
    PREVIOUS_PAGE: 'PREVIOUS_PAGE',
    RESET_PAGE: 'RESET_PAGE',
    CHANGE_SIZE: 'CHANGE_SIZE',
}

export const actions = {
    //PATIENTS
    LOAD_PATIENTS_FROM_DB_TO_STORE: 'LOAD_PATIENTS_FROM_DB_TO_STORE',
    CHANGE_NUMBER_OF_MONTH_TO_FILTER: 'CHANGE_NUMBER_OF_MONTH_TO_FILTER',

    //PHARMACIES
    LOAD_PHARMACIES_FROM_DB_TO_STORE: 'LOAD_PHARMACIES_FROM_DB_TO_STORE',

    //MEDICATIONS
    LOAD_MEDICATIONS_FROM_DB_TO_STORE: 'LOAD_MEDICATIONS_FROM_DB_TO_STORE',

    //STORE
    ASSIGN_PATIENT_TO_PHARMACY: 'ASSIGN_PATIENT_TO_PHARMACY',
    INITIALIZATION: 'INITIALIZATION',
}

export const namespacedGetters = {
    //PATIENTS
    FILTERED_PATIENTS: PatientsPath + getters.FILTERED_PATIENTS,
    PATIENTS_COUNT: PatientsPath + getters.PATIENTS_COUNT,
    PATIENTS_AT_CURRENT_PAGE: PatientsPath + getters.PATIENTS_AT_CURRENT_PAGE,
    IS_PATIENT_ASSIGNED_TO_PHARMACY: PatientsPath + getters.IS_PATIENT_ASSIGNED_TO_PHARMACY,
    PATIENTS_PAGE_COUNT: PatientsPath + getters.PATIENTS_PAGE_COUNT,
    PATIENT_INDEX: PatientsPath + getters.PATIENT_INDEX,
    PATIENT_RELATED_PHARMACY_INDEX: PatientsPath + getters.PATIENT_RELATED_PHARMACY_INDEX,
    GET_PATIENT_BY_ID: PatientsPath + getters.GET_PATIENT_BY_ID,

    //PHARMACIES
    PHARMACIES: PharmaciesPath + getters.PHARMACIES,
    PHARMACIES_COUNT: PharmaciesPath + getters.PHARMACIES_COUNT,
    PHARMACIES_AT_CURRENT_PAGE: PharmaciesPath + getters.PHARMACIES_AT_CURRENT_PAGE,
    PHARMACIES_PAGE_COUNT: PharmaciesPath + getters.PHARMACIES_PAGE_COUNT,
    PHARMACY_INDEX: PharmaciesPath + getters.PHARMACY_INDEX,
    PHARMACY_RELATED_PATIENT_INDEX: PharmaciesPath + getters.PHARMACY_RELATED_PATIENT_INDEX,
    GET_PHARMACY_BY_ID: PharmaciesPath + getters.GET_PHARMACY_BY_ID,

    //MEDICATIONS
    MEDICATIONS: MedicationsPath + getters.MEDICATIONS,

    //AUTH
    AUTH_ROLE: AuthPath + getters.AUTH_ROLE,
    AUTH_ID: AuthPath + getters.AUTH_ID,

    //PATIENTS PAGE
    PATIENTS_ITEMS_FROM: PatientsPath + PagePath + getters.ITEMS_FROM,
    PATIENTS_ITEMS_TO: PatientsPath + PagePath + getters.ITEMS_TO,
    PATIENTS_PAGE_SIZE: PatientsPath + PagePath + getters.PAGE_SIZE,

    //PHARMACIES PAGE
    PHARMACIES_ITEMS_FROM: PharmaciesPath + PagePath + getters.ITEMS_FROM,
    PHARMACIES_ITEMS_TO: PharmaciesPath + PagePath + getters.ITEMS_TO,
    PHARMACIES_PAGE_SIZE: PharmaciesPath + PagePath + getters.PAGE_SIZE,

    //PAGE RELATED PATH
    PAGE_ITEMS_FROM: PagePath + getters.ITEMS_FROM,
    PAGE_ITEMS_TO: PagePath + getters.ITEMS_TO,
    PAGE_PAGE_SIZE: PagePath + getters.PAGE_SIZE,
}

export const namespacedMutations = {
    //PATIENTS
    PATIENT_ADD_PHARMACY: PatientsPath + mutations.PATIENT_ADD_PHARMACY,
    PATIENT_REMOVE_PHARMACY: PatientsPath + mutations.PATIENT_REMOVE_PHARMACY,
    LOAD_PATIENTS_TO_STORE: PatientsPath + mutations.LOAD_PATIENTS_TO_STORE,
    SET_NUMBER_OF_MONTH_TO_FILTER: PatientsPath + mutations.SET_NUMBER_OF_MONTH_TO_FILTER,
    IS_PATIENT_ASSIGNED_TO_PHARMACY: PatientsPath + mutations.IS_PATIENT_ASSIGNED_TO_PHARMACY,

    //PHARMACIES
    LOAD_PHARMACIES_TO_STORE: PharmaciesPath + mutations.LOAD_PHARMACIES_TO_STORE,
    PHARMACY_ADD_PATIENT: PharmaciesPath + mutations.PHARMACY_ADD_PATIENT,
    PHARMACY_REMOVE_PATIENT: PharmaciesPath + mutations.PHARMACY_REMOVE_PATIENT,

    //MEDICATIONS
    LOAD_MEDICATIONS_TO_STORE: MedicationsPath + mutations.LOAD_MEDICATIONS_TO_STORE,

    //AUTH
    AUTH_LOGIN: AuthPath + mutations.AUTH_LOGIN,
    AUTH_LOGOUT: AuthPath + mutations.AUTH_LOGOUT,

    //PATIENTS PAGE
    PATIENTS_NEXT_PAGE: PatientsPath + PagePath + mutations.NEXT_PAGE,
    PATIENTS_PREVIOUS_PAGE: PatientsPath + PagePath + mutations.PREVIOUS_PAGE,
    PATIENTS_RESET_PAGE: PatientsPath + PagePath + mutations.RESET_PAGE,
    PATIENTS_CHANGE_SIZE: PatientsPath + PagePath + mutations.CHANGE_SIZE,

    //PHARMACIES PAGE
    PHARMACIES_NEXT_PAGE: PharmaciesPath + PagePath + mutations.NEXT_PAGE,
    PHARMACIES_PREVIOUS_PAGE: PharmaciesPath + PagePath + mutations.PREVIOUS_PAGE,
    PHARMACIES_RESET_PAGE: PharmaciesPath + PagePath + mutations.RESET_PAGE,
    PHARMACIES_CHANGE_SIZE: PharmaciesPath + PagePath + mutations.CHANGE_SIZE,

    //PAGE RELATED PATH
    PAGE_RESET_PAGE: PagePath + mutations.RESET_PAGE,
}

export const namespacedActions = {
    //PATIENTS
    LOAD_PATIENTS_FROM_DB_TO_STORE: PatientsPath + actions.LOAD_PATIENTS_FROM_DB_TO_STORE,
    CHANGE_NUMBER_OF_MONTH_TO_FILTER: PatientsPath + actions.CHANGE_NUMBER_OF_MONTH_TO_FILTER,

    //PHARMACIES
    LOAD_PHARMACIES_FROM_DB_TO_STORE: PharmaciesPath + actions.LOAD_PHARMACIES_FROM_DB_TO_STORE,

    //MEDICATIONS
    LOAD_MEDICATIONS_FROM_DB_TO_STORE: MedicationsPath + actions.LOAD_MEDICATIONS_FROM_DB_TO_STORE,

    //STORE
    ASSIGN_PATIENT_TO_PHARMACY: actions.ASSIGN_PATIENT_TO_PHARMACY,
    INITIALIZATION: actions.INITIALIZATION,
}

