export const getters = {
    //PATIENTS
    FILTERED_PATIENTS: 'FILTERED_PATIENTS',
    NUMBER_OF_PATIENTS: 'NUMBER_OF_PATIENTS',
    PATIENTS_AT_CURRENT_PAGE: 'PATIENTS_AT_CURRENT_PAGE',
    IS_PATIENT_ASSIGNED_TO_PHARMACY: 'IS_PATIENT_ASSIGNED_TO_PHARMACY',
    GET_PATIENTS_PAGE_COUNT: 'GET_PATIENTS_PAGE_COUNT',
    PATIENT_INDEX: 'PATIENT_INDEX',
    RELATED_TO_PATIENT_PHARMACY_INDEX: 'RELATED_TO_PATIENT_PHARMACY_INDEX',
    GET_PATIENT_BY_ID: 'GET_PATIENT_BY_ID',

    //PHARMACIES
    PHARMACIES: 'PHARMACIES',
    NUMBER_OF_PHARMACIES: 'NUMBER_OF_PHARMACIES',
    PHARMACIES_AT_CURRENT_PAGE: 'PHARMACIES_AT_CURRENT_PAGE',
    GET_PHARMACIES_PAGE_COUNT: 'GET_PHARMACIES_PAGE_COUNT',
    PHARMACY_INDEX: 'PHARMACY_INDEX',
    RELATED_TO_PHARMACY_PATIENT_INDEX: 'RELATED_TO_PHARMACY_PATIENT_INDEX',
    GET_PHARMACY_BY_ID: 'GET_PHARMACY_BY_ID',

    //PAGE
    ITEMS_FROM: 'ITEMS_FROM',
    ITEMS_TO: 'ITEMS_TO',
    PAGE_SIZE: 'PAGE_SIZE',
}

export const mutations = {
    //PATIENTS
    PATIENT_ADD_PHARMACY: 'PATIENT_ADD_PHARMACY',
    PATIENT_REMOVE_PHARMACY: 'PATIENT_REMOVE_PHARMACY',
    LOAD_PATIENTS_TO_STORE: 'LOAD_PATIENTS_TO_STORE',
    SET_NUMBER_OF_MONTH_TO_FILTER: 'SET_NUMBER_OF_MONTH_TO_FILTER',
    IS_PATIENT_ASSIGNED_TO_PHARMACY: 'IS_PATIENT_ASSIGNED_TO_PHARMACY',
    PATIENT_INDEX: 'PATIENT_INDEX',
    RELATED_PHARMACY_INDEX: 'RELATED_PHARMACY_INDEX',

    //PHARMACIES
    LOAD_PHARMACIES_TO_STORE: 'LOAD_PHARMACIES_TO_STORE',
    PHARMACY_ADD_PATIENT: 'PHARMACY_ADD_PATIENT',
    PHARMACY_REMOVE_PATIENT: 'PHARMACY_REMOVE_PATIENT',

    //PAGE
    NEXT_PAGE: 'NEXT_PAGE',
    PREVIOUS_PAGE: 'PREVIOUS_PAGE',
    RESET_PAGE: 'RESET_PAGE',
    CHANGE_SIZE: 'CHANGE_SIZE',
}

export const actions = {
    //PATIENTS
    LOAD_PATIENTS_FROM_DB_TO_STORE: 'LOAD_PATIENTS_FROM_DB_TO_STORE',
    CHANGE_NUMBER_OF_MONTH_TO_FILTER: 'CHANGE_NUMBER_OF_MONTH_TO_FILTER',

    //PHARMACIES
    LOAD_PHARMACIES_FROM_DB_TO_STORE: 'LOAD_PHARMACIES_FROM_DB_TO_STORE',

    //STORE
    ASSIGN_PATIENT_TO_PHARMACY: 'ASSIGN_PATIENT_TO_PHARMACY',
    INITIALIZATION: 'INITIALIZATION',
}

